version: '3'

networks:
  questionnaire-backend:

volumes:
  questionnaire-data:

services:
  api:
    image: ci.tno.nl/caic/questionnaire:latest
    build:
      context: .
    env_file:
      - .env
    networks:
      - questionnaire-backend
    stop_signal: SIGKILL
    ports:
      #- 80:8082
      #- 8080:8080
      - 8082:8082

  front-end:
    build:
      context: ../front-end
    env_file:
      - .env
    networks:
      - questionnaire-backend
    stop_signal: SIGKILL
    ports:
      - 80:80
      #- 8080:8080
      #- 8082:8082
      
  mongodb:
    image: mongo
    volumes:
      - questionnaire-data:/etc/mongo
    env_file:
      - .env
    networks:
      - questionnaire-backend
    #ports:
    #  - 27017:27017
  
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    networks:
      - questionnaire-backend
    env_file:
      - .env
